"""Alembic environment.

The URL comes from the application's own settings rather than alembic.ini, so
migrations always target the database the service is configured for and no
credential is ever committed. ``-x url=...`` overrides it, which is how the test
suite points a migration run at a throwaway database.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.pool import NullPool

from app.config.settings import get_settings
from app.db.base import Base

# Importing the models registers them on Base.metadata for autogenerate.
from app.db import models  # noqa: F401  (side-effect import)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _database_url() -> str:
    """Resolve the URL: -x url=... wins, then DATABASE_URL from settings."""
    override = context.get_x_argument(as_dictionary=True).get("url")
    if override:
        return override

    url = get_settings().DATABASE_URL
    if not url:
        raise RuntimeError(
            "No database configured. Set DATABASE_URL, or pass one explicitly:\n"
            "  alembic -x url=postgresql+asyncpg://... upgrade head"
        )
    return url


def _include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep PostGIS's own bookkeeping out of autogenerated migrations."""
    if type_ == "table" and name in {"spatial_ref_sys", "geography_columns",
                                     "geometry_columns", "raster_columns",
                                     "raster_overviews"}:
        return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=_include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=_include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations against a live database."""
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = _database_url()

    engine = async_engine_from_config(
        configuration, prefix="sqlalchemy.", poolclass=NullPool
    )
    try:
        async with engine.connect() as connection:
            await connection.run_sync(_run)
    finally:
        await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
