"""Initial schema: PostGIS, observations, forecasts.

Hand-written rather than autogenerated. GeoAlchemy2 emits its own DDL for
spatial columns and indexes, and letting autogenerate guess at that produces
migrations that create the same index twice or drop one they cannot recreate.
Spelling it out keeps the migration reversible and reviewable.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-04
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SRID = 4326


def _geography_column() -> sa.Column:
    # spatial_index=False: the GIST indexes are created explicitly below so
    # they carry names this migration can also drop.
    return sa.Column(
        "geom",
        Geography(geometry_type="POINT", srid=SRID, spatial_index=False),
        nullable=False,
    )


def upgrade() -> None:
    # PostGIS supplies the geography type and the ST_* functions the spatial
    # queries depend on. IF NOT EXISTS keeps this safe on an image that already
    # enabled it.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "weather_observations",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        # Place
        sa.Column("location_key", sa.String(length=32), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        _geography_column(),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        # Provenance
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("provider_name", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=64), server_default="", nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=True),
        sa.Column("license", sa.String(length=128), nullable=True),
        sa.Column("attribution", sa.String(length=256), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Condition
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("condition_description", sa.String(length=128), nullable=True),
        sa.Column("wmo_code", sa.SmallInteger(), nullable=True),
        # Time
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        # Measurements
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_c", sa.Float(), nullable=True),
        sa.Column("dew_point_c", sa.Float(), nullable=True),
        sa.Column("relative_humidity_pct", sa.Float(), nullable=True),
        sa.Column("pressure_msl_hpa", sa.Float(), nullable=True),
        sa.Column("surface_pressure_hpa", sa.Float(), nullable=True),
        sa.Column("wind_speed_ms", sa.Float(), nullable=True),
        sa.Column("wind_gust_ms", sa.Float(), nullable=True),
        sa.Column("wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("cloud_cover_pct", sa.Float(), nullable=True),
        sa.Column("visibility_m", sa.Float(), nullable=True),
        sa.Column("uv_index", sa.Float(), nullable=True),
        sa.Column("is_day", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_weather_observations"),
        sa.UniqueConstraint(
            "provider_id",
            "model",
            "location_key",
            "observed_at",
            name="uq_weather_observations_identity",
        ),
    )
    op.create_index(
        "ix_weather_observations_location_key_observed_at",
        "weather_observations",
        ["location_key", "observed_at"],
    )
    op.create_index(
        "ix_weather_observations_observed_at", "weather_observations", ["observed_at"]
    )
    op.create_index(
        "ix_weather_observations_provider_id", "weather_observations", ["provider_id"]
    )
    op.create_index(
        "ix_weather_observations_geom",
        "weather_observations",
        ["geom"],
        postgresql_using="gist",
    )

    op.create_table(
        "weather_forecasts",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("location_key", sa.String(length=32), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        _geography_column(),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("provider_name", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=64), server_default="", nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=True),
        sa.Column("license", sa.String(length=128), nullable=True),
        sa.Column("attribution", sa.String(length=256), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # The two timestamps that make forecast-skill analysis possible.
        sa.Column("forecast_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution", sa.String(length=8), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("condition_description", sa.String(length=128), nullable=True),
        sa.Column("wmo_code", sa.SmallInteger(), nullable=True),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("temperature_min_c", sa.Float(), nullable=True),
        sa.Column("temperature_max_c", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_c", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_min_c", sa.Float(), nullable=True),
        sa.Column("apparent_temperature_max_c", sa.Float(), nullable=True),
        sa.Column("dew_point_c", sa.Float(), nullable=True),
        sa.Column("relative_humidity_pct", sa.Float(), nullable=True),
        sa.Column("pressure_msl_hpa", sa.Float(), nullable=True),
        sa.Column("wind_speed_ms", sa.Float(), nullable=True),
        sa.Column("wind_gust_ms", sa.Float(), nullable=True),
        sa.Column("wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("precipitation_probability_pct", sa.Float(), nullable=True),
        sa.Column("precipitation_hours", sa.Float(), nullable=True),
        sa.Column("cloud_cover_pct", sa.Float(), nullable=True),
        sa.Column("visibility_m", sa.Float(), nullable=True),
        sa.Column("uv_index", sa.Float(), nullable=True),
        sa.Column("is_day", sa.Boolean(), nullable=True),
        sa.Column("sunrise", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sunset", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_weather_forecasts"),
        sa.UniqueConstraint(
            "provider_id",
            "model",
            "location_key",
            "resolution",
            "forecast_created_at",
            "forecast_for",
            name="uq_weather_forecasts_identity",
        ),
    )
    op.create_index(
        "ix_weather_forecasts_location_key_forecast_for",
        "weather_forecasts",
        ["location_key", "forecast_for"],
    )
    op.create_index(
        "ix_weather_forecasts_forecast_created_at_forecast_for",
        "weather_forecasts",
        ["forecast_created_at", "forecast_for"],
    )
    op.create_index(
        "ix_weather_forecasts_provider_id", "weather_forecasts", ["provider_id"]
    )
    op.create_index(
        "ix_weather_forecasts_geom",
        "weather_forecasts",
        ["geom"],
        postgresql_using="gist",
    )


def downgrade() -> None:
    op.drop_index("ix_weather_forecasts_geom", table_name="weather_forecasts")
    op.drop_index("ix_weather_forecasts_provider_id", table_name="weather_forecasts")
    op.drop_index(
        "ix_weather_forecasts_forecast_created_at_forecast_for",
        table_name="weather_forecasts",
    )
    op.drop_index(
        "ix_weather_forecasts_location_key_forecast_for",
        table_name="weather_forecasts",
    )
    op.drop_table("weather_forecasts")

    op.drop_index("ix_weather_observations_geom", table_name="weather_observations")
    op.drop_index(
        "ix_weather_observations_provider_id", table_name="weather_observations"
    )
    op.drop_index(
        "ix_weather_observations_observed_at", table_name="weather_observations"
    )
    op.drop_index(
        "ix_weather_observations_location_key_observed_at",
        table_name="weather_observations",
    )
    op.drop_table("weather_observations")

    # The extension is left in place: other schemas in the same database may
    # depend on it, and dropping it is not this migration's business.
